# Generated by Django 5.1.5 on 2026-08-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_merge_0002_product_cutout_url_0002_store_muse_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('backpack', '백팩'), ('tote', '토트백'), ('crossbody', '크로스백'), ('shoulder', '숄더백'), ('wallet', '지갑'), ('accessory', '액세서리'), ('clothing', '의류')], max_length=20),
        ),
    ]
