# Generated by Django 5.1.5 on 2026-08-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="external_url",
            field=models.URLField(max_length=2048),
        ),
    ]
