# Generated by Django 5.1.5 on 2026-08-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_external_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cutout_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
